Algoritmo "testeCaracter"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Recebe um valor caractere, armazena na variável nome e depois informa ao usuário
// Autor(a)    : Alvaro Carvalho de Lima
// Data atual  : 05/09/2022
Var
// Seção de Declarações das variáveis 
nome:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite seu nome: ")
leia(nome)
Escreval("O nome digitado é: ", nome)


Fimalgoritmo